edition = "2021"

# Stable Features
reorder_imports = true

# Unstable Features
unstable_features=true
wrap_comments = true
comment_width = 80
condense_wildcard_suffixes = true
enum_discrim_align_threshold = 30
fn_args_layout = "Vertical"
